#!/bin/bash

cd "$(dirname "$0")"

source includes/projects

print_usage() {
    echo "💀 $1"
    echo "Help below 👇"
    echo ""
    echo "Runs the tests of the specified project."
    echo ""
    echo "Usage: ./test <project>"
    ./projects
    exit 1
}

if [ -z "$1" ]; then
    print_usage "Project name is missing!"
fi

cd ..

nx test ${project_names[$1]} $2
