import { InjectedConnector } from "@web3-react/injected-connector";
import { SafeAppConnector } from "@gnosis.pm/safe-apps-web3-react";
import { WalletConnectConnector } from "@web3-react/walletconnect-connector";
import { Web3Provider } from "@ethersproject/providers";
import { NetworkConnector } from "@web3-react/network-connector";
export declare const RPC_URLS: Record<number, string>;
export declare const network: NetworkConnector;
export declare const injected: InjectedConnector;
export default function getLibrary(provider: any): Web3Provider;
export declare const gnosisSafe: SafeAppConnector;
export declare const walletconnect: WalletConnectConnector;
